### ISSUE TITLE
Update the example composer.json

### ISSUE THREAD

**Issue by BronsonQuick** [humanmade/hm-base#79]
>I'd have also added `"content/{$name}/": [ "type:wordpress-dropin" ]` for drop-ins support, and depending on what kind of versioning schema `humanmade/coding-standards` uses, would have used a different versioning restrain, e.g. `~` or `>`.

As per Mr Gibbs [comment](https://github.com/humanmade/hm-base/pull/78#issuecomment-419365227)! 💖

**Comment by tfrommen** [comment]
A couple things that come to my mind...

* The license should be a valid SPDX license ID: `"license": "GPL-3.0-or-later"`.
* I'd recommend to use the property order presented in the [official documentation](https://getcomposer.org/doc/04-schema.md), so, for example, `"minimum-stability"` should be the second last (in this example file), just before `"extra"`.
* Why not specify the minimum PHP version? `"require": { "php": ">=7.0" }`. This should be the very first entry in the `"require"` section.
* Since we use this for **websites**, and not plugins or so, the `"type"` is missing/incorrect. By default, it is `"library"`, but we'd want it to be `"type": "project"`, right?
* The `"minimum-stability"`, by default, **is** `"stable"`, so this is redundant. However, I'm wondering if we should have it set to `"dev"``, and then, of course, also define `"prefer-stable": true`...? This is what I see the most.
* We should define the [_platform_ PHP version](https://getcomposer.org/doc/06-config.md#platform), and so define what gets written into the `composer.lock` file.
* I don't know `oomphinc/composer-installers-extender`. What do we need it for? If we use `mu-plugins` (see dev chat), we don't!
* [`composer-installers` supports dropins}(https://github.com/composer/installers/blob/master/src/Composer/Installers/WordPressInstaller.php) out of the box, so no need to specify that yourself (talking about Paul's comment here).

**Comment by paulgibbs** [comment]
I think worrying about the precise ordering of the contents in the JSON file is obsessing too much over a tiny detail, for a base project template. If a project wanted to care about that, then they can add `composer-normalize` there...

**Comment by paulgibbs** [comment]
> composer-installers supports dropins out of the box, so no need to specify that yourself (talking about Paul's comment here).

Except we do, because this base project has it in `content/` and `composer-installers` defaults to `wp-content/`. :)

**Comment by mikeselander** [comment]
> I don't know oomphinc/composer-installers-extender. What do we need it for? If we use mu-plugins (see dev chat), we don't!

This is because quite a few plugins and libraries don't identify themselves with a proper type or come from Packagist which means we need a way to manually define where they're going to go. For example, [Extended Template Parts](https://github.com/johnbillion/extended-template-parts/blob/master/composer.json) registers a Composer file, but not a type.

> The "minimum-stability", by default, is "stable", so this is redundant. However, I'm wondering if we should have it set to "dev", and then, of course, also define "prefer-stable": true...? This is what I see the most.

What do you recommend that we put here?

**Comment by mikeselander** [comment]
Working through these addition in #84 - Feel free to make addendums.

**Comment by mikeselander** [comment]
We've addressed all the feedback from this ticket now.
